#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
import platform
from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *
from PyQt5.QtCore import pyqtSlot

from PyQt5 import QtCore, QtGui, QtWidgets

# My imports
from basketball_Reference_bs4 import *
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(609, 357)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setGeometry(QRect(3, 3, 600, 350))
        self.frame.setTabletTracking(False)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.982955, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(32, 61, 135, 255));\n"
"border-radius: 20px;")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName(u"frame")
        self.label = QLabel(self.frame)
        self.label.setGeometry(QRect(150, 10, 351, 51))
        font = QFont()
        font.setFamily("DIN Condensed")
        font.setPointSize(40)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background: transparent;")
        self.label.setObjectName(u"label")
        self.input_lineEdit = QLineEdit(self.frame)
        self.input_lineEdit.setGeometry(QRect(140, 60, 361, 41))
        font = QFont()
        font.setFamily("DIN Condensed")
        font.setPointSize(22)
        self.input_lineEdit.setFont(font)
        self.input_lineEdit.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-color: rgb(0, 0, 0);")
        self.input_lineEdit.setObjectName(u"input_lineEdit")
        self.search_pushButton = QPushButton(self.frame)
        self.search_pushButton.setGeometry(QRect(270, 120, 91, 41))
        font = QFont()
        font.setFamily("DIN Condensed")
        font.setPointSize(20)
        self.search_pushButton.setFont(font)
        self.search_pushButton.setLayoutDirection(Qt.LeftToRight)
        self.search_pushButton.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.search_pushButton.setObjectName(u"search_pushButton")
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setGeometry(QRect(10, 60, 121, 251))
        self.frame_2.setToolTip("")
        self.frame_2.setStyleSheet("image: url(/Users/nicholausbrell/Desktop/all_nba_app/images/nba-logo-transparent.png);\n"
"")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setObjectName(u"frame_2")
        self.label_stats = QLabel(self.frame)
        self.label_stats.setGeometry(QRect(140, 170, 361, 131))
        font = QFont()
        font.setFamily("Courier")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_stats.setFont(font)
        self.label_stats.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_stats.setObjectName("label_stats")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

        # connecting action when the button is clicked
        self.search_pushButton.clicked.connect(self.on_click)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">Search for a Player\'s Stats</span></p></body></html>"))
        self.search_pushButton.setText(_translate("MainWindow", "Search"))
        

    @pyqtSlot()
    def on_click(self):
        print("button clicked")
        player     = self.input_lineEdit.text()
        player_URL = gen_player_link(player)
        player_stats = get_player_stats(player_URL, player)

        # reset color and background for 'label'
        self.label.setStyleSheet("color:#ff0000;\n"
                                 "background: transparent;")

        self.label_stats.setText("label_stats")

        # clear text in 'input_lineEdit'
        self.input_lineEdit.clear()


"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
"""